server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/durak
spring.datasource.username=durak
spring.datasource.password=durak123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=durak
spring.rabbitmq.password=durak123
spring.rabbitmq.virtual-host=/
